services:
  auth-service:
    build: ./users
    container_name: auth-service
    ports:
      - "8000:8000"
    depends_on:
      auth-db:
        condition: service_healthy
    environment:
      DB_NAME: trello_auth
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: auth-db
      DB_PORT: 5432
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  auth-db:
    image: postgres:16
    container_name: auth-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trello_auth
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5
