version: "3.9"

services:

  auth-service:
    build: ./users
    container_name: auth-service
    ports:
      - "8000:8000"
    depends_on:
      - auth-db
      - auth-celery
      - rabbitmq
    environment:
      DB_NAME: trello_auth
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: auth-db
      DB_PORT: 5432
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    volumes: 
      - ./users:/app

  auth-db:
    image: postgres:16
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trello_auth
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4.7-alpine
    container_name: redis-service
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.2.1-management
    container_name: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  auth-celery:
    build: ./users
    container_name: auth-celery
    depends_on:
      - redis
      - rabbitmq
    environment:
      DB_NAME: trello_auth
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: auth-db
      DB_PORT: 5432
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    command: sh -c "celery -A users worker --loglevel=info"
